music-library {
  postgres {
    url = "jdbc:postgresql://localhost:5432/music_library"
    url = "jdbc:postgresql://192.168.0.20:5432/music_library"
    url = ${?MUSIC_LIBRARY_POSTGRES_URL}
    user = "postgres"
    user = ${?MUSIC_LIBRARY_POSTGRES_USER}
    password = ""
    password = "homeassistant"
    password = ${?MUSIC_LIBRARY_POSTGRES_PASSWORD}
  }
}
